"""baseline

Drops predictions/positions/model_runs - leftover physical tables from the
deleted LightGBM pipeline that outlived its code (see docs/PROGRESS.md).
Every other table already matches the current models exactly, so this is
the only real change; everything after this revision is a genuine schema
change instead of a manual DROP TABLE + init_db.py.

These tables only exist on databases that ran the old pipeline (e.g. local
dev) - a fresh database (CI, a new clone) never has them, so the drops are
guarded on table existence rather than assumed unconditionally.

Revision ID: ccac238a7652
Revises:
Create Date: 2026-09-13 12:12:03.515925

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccac238a7652"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())

    if "predictions" in existing:
        op.drop_index(op.f("ix_predictions_date"), table_name="predictions")
        op.drop_table("predictions")
    if "positions" in existing:
        op.drop_index(op.f("ix_positions_date"), table_name="positions")
        op.drop_table("positions")
    if "model_runs" in existing:
        op.drop_table("model_runs")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "published_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("oof_source", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("construction", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("as_of", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("n_dates", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("n_symbols", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("rank_ic", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
        sa.Column("icir", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
        sa.Column(
            "ic_hit_rate", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column(
            "q_spread", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sharpe_10bps", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column(
            "turnover", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column(
            "break_even_bps", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column("shap_json", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("params_json", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("model_runs_pkey")),
    )
    op.create_table(
        "positions",
        sa.Column("symbol", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("weight", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
        sa.Column("construction", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"], ["symbols.symbol"], name=op.f("positions_symbol_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("symbol", "date", name=op.f("positions_pkey")),
    )
    op.create_index(op.f("ix_positions_date"), "positions", ["date"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("symbol", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("pred", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
        sa.Column("label", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
        sa.Column("source", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"], ["symbols.symbol"], name=op.f("predictions_symbol_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("symbol", "date", name=op.f("predictions_pkey")),
    )
    op.create_index(op.f("ix_predictions_date"), "predictions", ["date"], unique=False)
    # ### end Alembic commands ###
